### ISSUE TITLE
Is there support for Compose Multiplatform applications?

### ISSUE THREAD

**Issue by MessiasLima** [maxkeppeler/sheets-compose-dialogs#1]
Hello Author! Thank you so much for your amazing job! I would like to ask if this lib supports multi-platform applications. If not... is there any will to add this support?

Thank you one more time!

**Comment by maxkeppeler** [comment]
Hey! Thanks man, it was really a lot of work! It does not support multi-platform apps. I would like to support it! However, I currently did not yet have the time to learn this topic and therefore can't add the support to my lib for it. If you know more how to support it, just let me know. Definitely open for it.

**Comment by russellbanks** [comment]
@maxkeppeler, could we keep this open? This would be good to look into, especially as Compose for IOS is now in alpha.
