### ISSUE TITLE
Background color is light even in dark mode.

### ISSUE THREAD

**Issue by p0ppy-fl0w3r** [maxkeppeler/sheets-compose-dialogs#12]
The background color doesn't seem to change to a darker color even if the device is in dark mode. My surface color is 0xFF26282F but the dialog is shown in a 'white' color.  

![Screenshot_20230106_160604_Hydro Bro (1)](https://user-images.githubusercontent.com/85251913/210987319-50e97f2c-f8ab-4fbd-9cd6-caebde0be91a.jpg) ![Screenshot_20230106_160617_Hydro Bro](https://user-images.githubusercontent.com/85251913/210987420-910cc6aa-9084-44b0-9f7e-4b390e517ffa.jpg)

**Comment by maxkeppeler** [comment]
On first sight, in the file `DialogBase` the `Surface` is used to wrap the use-case layout in it. 
Surface uses as background `MaterialTheme.colorScheme.surface`

Can u maybe show your theme setup? Right now, it's difficult to guess what the problem could be.

**Comment by p0ppy-fl0w3r** [comment]
Sure!

Here's the color palette 

```
val Blue500 = Color(0xFF1E80B9)
val DarkBlue900 = Color(0xFF26282F)

// The app is always in dark mode regardless of the user's system theme.
val ColorPalette = darkColors(
    primary = Blue500,
    surface = DarkBlue900,
    onSurface = Color.White,
    background = DarkBlue900,
    onBackground = Color.White
)
```

... and the app's theme.
```
@Composable
fun MyTheme(content: @Composable () -> Unit) {

    MaterialTheme(colors = ColorPalette, typography = Typography, content = content)
}
```

In addition to the code above, I've added `android:windowBackground=@color/black` to my res/values/theme.xml to make the background color of my splash screen black. Here's the entirety of the theme.xml file.

```
<?xml version="1.0" encoding="utf-8"?>
<resources>

    <style name="Theme.MyApp" parent="android:Theme.Material.Light.NoActionBar" >
        <item name="android:windowBackground">@color/black</item>
    </style>
</resources>
```

**Comment by maxkeppeler** [comment]
Are you using MD2 or MD3? Perhaps some problem then, as for issue #15

**Comment by p0ppy-fl0w3r** [comment]
Yep... I'm using MD2.  Thankx for this awesome library tho : )

**Comment by maxkeppeler** [comment]
Sorry for the issue then. I will definitely look into supporting MD2 as separate dependencies in the future, alongside landscape Layouts, once I find more time! Thank you!
