### ISSUE TITLE
onPositiveButton, onNegativeButton lambdas

### ISSUE THREAD

**Issue by stevdza-san** [maxkeppeler/sheets-compose-dialogs#13]
I would suggest adding different kind of lambdas inside the SheetState. Like for example, I want to implement a different logic when I press Ok, and not use the same logic for Cancel button as well. onFinishedRequest() is used for all buttons, but I cannot distinguish positive and negative buttons in any way.  Good library btw. :)

**Comment by maxkeppeler** [comment]
Hello Stefan, thanks a lot - especially happy to hear that from you! 

I don't see a need to add that to the `SheetState`, as it is already part of each use-case view/ dialog through the `*Selection`-class.

Here's an example with the `CoreDialog` & the respective `CoreSelection` class.
```
CoreDialog(
        state = rememberSheetState(),
        selection = CoreSelection(
            negativeButton = SelectionButton(stringResource(R.string.cancel)), // Example negative button
            positiveButton = SelectionButton(stringResource(android.R.string.ok)), // Example positive button
            onPositiveClick = {},  // Handle positive click
            onNegativeClick = {}, // Handle negative click
            onExtraButtonClick = {} // Handle extra button click
        ),
       ...
)
```

The idea behind the lambdas in the SheetState is, that they can be used to indicate that a use-case view is "done" - dunno if it is a positive or negative button click.
- In a BottomSheet, that means that the BottomSheet can be hidden. 
- In a dialog, it means the dialog will be closed (which is already handled with the Composable *Dialog functions).
- In a PopUp or any other container, it will close the PopUp or handle the container however it is necessary. 
 
In the sample app is an example how to use it with a BottomSheet and PopUp.

I might offer specific BottomSheet & PopUp Composable functions in the future for the use-case views and remove the lambdas in the SheetState. 

I will keep working more on the lib again soon! If you have any ideas for improvement, let me know.

**Comment by stevdza-san** [comment]
Oh I did not know that, thank you for the detailed answer, I get it now. At the moment I do not have any more suggestions, everything seems to work the way it is supposed to. Planning to include this lib in my new upcoming course. :)

**Comment by maxkeppeler** [comment]
Alright. Wow, that's cool. Drop me a message and I can include your course / video in the README.md file of this library as well as in the notion documentation!
