### ISSUE TITLE
Button colors doesn't respect current theme

### ISSUE THREAD

**Issue by risalfajar** [maxkeppeler/sheets-compose-dialogs#15]
I tried to implement a simple confirmation dialog with `CoreDialog`, here's what I get:
![image](https://user-images.githubusercontent.com/28381124/213422365-2e562452-f9a1-4df4-91b2-fa0a6ca9fb4d.png)

Despite that the primary color is _blue_, the button that showed is _purple_, and there are no parameters I can pass to customize it.
I use Material2. Do you have any solution?

**Comment by maxkeppeler** [comment]
This library uses MD3. Mixing it with MD2 leads to issues with colors. 
If more people request it, I might support MD2 as separate dependencies.

**Comment by risalfajar** [comment]
Yes please. I've considered to use MD3 before, but sadly some components hasn't been supported yet.

**Comment by risalfajar** [comment]
### Workaround

You can add Material3 dependency and use it in your theme:
```kotlin
private val LightColorPalette = lightColors(
    primary = BrandBlue,
    primaryVariant = BrandBlue,
    secondary = BrandYellow,
    onPrimary = Color.White,
    onSecondary = Color.White,
    error = Red,
    onError = Color.White
)

@Composable
fun AppTheme(content: @Composable () -> Unit) {
    MaterialTheme(
        colors = LightColorPalette,
        typography = Typography,
        shapes = Shapes
    ) {
        androidx.compose.material3.MaterialTheme(
            colorScheme = androidx.compose.material3.MaterialTheme.colorScheme.copy(
                primary = LightColorPalette.primary,
                primaryContainer = LightColorPalette.primary,
                secondary = LightColorPalette.primary,
                secondaryContainer = LightColorPalette.primary,
                tertiary = LightColorPalette.secondary,
                tertiaryContainer = LightColorPalette.secondary,
                onPrimary = LightColorPalette.onPrimary,
                onSecondary = LightColorPalette.onPrimary,
                onTertiary = LightColorPalette.onSecondary,
                error = LightColorPalette.error,
                onError = LightColorPalette.onError,
                surface = LightColorPalette.surface,
                background = LightColorPalette.background
            ),
            androidx.compose.material3.MaterialTheme.shapes.copy(
                small = Shapes.small,
                medium = Shapes.medium,
                large = Shapes.large
            ),
            content = content
        )
    }
}
```

[Theming Guide](https://developer.android.com/jetpack/compose/designsystems/material2-material3#theming).
You can also use [Material3 Theme Builder](https://m3.material.io/theme-builder#/custom) to generate M3 theme.

**Comment by gibranhit** [comment]
> 

it's works, thanks

**Comment by thomasponzo-dev** [comment]
what color is used for what?  primary = LightColorPalette.primary,
                primaryContainer = LightColorPalette.primary,
                secondary = LightColorPalette.primary,
                secondaryContainer = LightColorPalette.primary,
                tertiary = LightColorPalette.secondary,
                tertiaryContainer = LightColorPalette.secondary,
                onPrimary = LightColorPalette.onPrimary,
                onSecondary = LightColorPalette.onPrimary,
                onTertiary = LightColorPalette.onSecondary,
                error = LightColorPalette.error,
                onError = LightColorPalette.onError,
                surface = LightColorPalette.surface,
                background = LightColorPalette.background
                I want to know for calendarview I need to change all the purple colors to a different one .
