### ISSUE TITLE
[CalendarDialog] when using disabledTimeline property, disabled days are not shown instead of being disabled

### ISSUE THREAD

**Issue by Nek-12** [maxkeppeler/sheets-compose-dialogs#18]
Using `disabledTimeline = PAST` or `FUTURE` results in disabled days not being shown in the dialog, which in turn results in the following representation: 

<details>
  <summary>Spoiler</summary>
  
  
![Screenshot_20230125-223026](https://user-images.githubusercontent.com/46318640/214669191-d3df9068-f885-4ec2-8856-759387b043f8.png)

  
</details>

Which looks unsightly. This behavior is not customizable. 

Proposed solution: add a parameter that would allow disabled days to show up as "greyed-out".

Update: because of the issue above, for months that are lacking any enabled days, the dialog is completely empty.

**Comment by maxkeppeler** [comment]
I agree. I will make them look exactly like individually disabled dates. 
Regarding your update: when the past or future is disabled, you are not supposed to be able to navigate to the past or future months and years. How did you manage to do that?

**Comment by Nek-12** [comment]
Oof, I will create a new issue for that
