### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by jemshit** [maxkeppeler/sheets-compose-dialogs#2]
Please compress the images on readme.md (tinypng.com)

**Comment by maxkeppeler** [comment]
They are GIFs. I already reduced their quality before. I noticed the colors change if I reduce the quality even further. I check what I can do.

**Comment by maxkeppeler** [comment]
After some more releases and improvements I will screenshot all the views as views, dialogs, bottom sheets and popups and present them. It's just so much work to do that. I will use optimized images instead of gifs.

**Comment by javimar** [comment]
Hi, is there doc for customizing, DateTimeDialog. Also, for this component, I have not seen the way to given a date already input, open the view with that date already.
Thanks!

**Comment by maxkeppeler** [comment]
Hi Javimar, there's no direct color customization, but you can just wrap it into your own MD3 theme to change colors. With the latest update (1.1.1), there's a default selection of date / time and both for the DateTimeDialog.

**Comment by javimar** [comment]
Thanks Max.. can you please provide a quick example to change colors for DateTimeDialog using that approach? I already have a MaterialTheme design, but for instance, I would like to change the background color of the dialog itself.

**Comment by maxkeppeler** [comment]
The background color (of Surface()) is references to` MaterialTheme.colorScheme.surface`. 
So you would need to override that `surface` color in your theme.

```
darkColorScheme(
    surface = ...
}

lightColorScheme(
    surface = ...
}
```

**Comment by javimar** [comment]
Thanks for the tips.
One more thing on the Locale. I am adding this, but the month, day, and year appear in English. Mine should be in Spanish. Is there a way to change the language of the dialog?

```
config = DateTimeConfig(
            locale = Locale.getDefault(),
            minYear = 1935,
            maxYear = LocalDate.now().year
        ),
```

**Comment by maxkeppeler** [comment]
It should, could you create a separate issue for that?
