### ISSUE TITLE
(FR) Calendar: Max and Min date instead of just year

### ISSUE THREAD

**Issue by risalfajar** [maxkeppeler/sheets-compose-dialogs#21]
Hello, thanks again for this amazing library.
Just found one thing that is missing from calendar: date boundaries, something like:
```kotlin
CalendarDialog(
    state = calendarDialog,
    config = CalendarConfig(
        minDate = LocalDate.now().minusYears(1),
        maxDate = LocalDate.now().plusYears(1)
    ),
    selection = CalendarSelection.Date(selectedDate = value) {
        onValueChange(it)
    }
)
```

This use case cannot be done using either `disabledDates` or `disabledTimeline`.

**Comment by maxkeppeler** [comment]
You are welcome. Happy to receive feedback from you.
```
val minYear: Int
val maxYear: Int
```
I might just replace it with a date range.
`val boundary: ClosedRange<LocalDate>`

I would need to make some minor changes (for myself)
- [ ] Additional setup check if the years difference in the range is valid (at least more than 1 year)
- [ ] Use boundary for year selection view
- [ ] Respect boundary when setting up month selection view
- [ ] Respect boundary in calculation and mark dates as disabled if they are not within it.

**Comment by Akramhussain4** [comment]
Why the range should be > 1 year?

**Comment by maxkeppeler** [comment]
This would require some changes with the month and year selection state, and some small other modifications. I will close your other Issue and add a commit to allow any range.
