### ISSUE TITLE
(FR) Clock: Max and Min time 

### ISSUE THREAD

**Issue by Akramhussain4** [maxkeppeler/sheets-compose-dialogs#22]
Hi,

Love your work. I just had a FR for the clock dialog to have a time boundary where the user will only be able to select time within the specified boundary.

**Comment by Akramhussain4** [comment]
Any ETA on when we can possibly have this released?

**Comment by maxkeppeler** [comment]
Useful enhancement! Either with another small 1.0.X update or 1.1.0 with landscape support and MD2. Probably the first…within the next week(s), as usual no promises.
