### ISSUE TITLE
DateTime Dialog(DatePicker) not working on Physical Devices

### ISSUE THREAD

**Issue by ankur141295** [maxkeppeler/sheets-compose-dialogs#23]
The DateTime Dialog to select only dates is not working on Physical devices but it works on emulator as expected. On a physical device, it only shows to select date while month and year never shows.

The same behaviour can be seen in the [sample app](https://github.com/maxkeppeler/sheets-compose-dialogs/blob/main/app/sample.apk).

https://user-images.githubusercontent.com/45303991/216774340-080c3ea2-484f-4b0e-97b4-1390e0336293.mp4

**Comment by maxkeppeler** [comment]
The view uses by default the localized date and time pattern with the specified `FormatStyle` and `Locale`. 
The idea was to let the view build up an input based on the pattern, the locale and the format style in the matching order of a date or time. 

Defaults are like this:
```
    override val locale: Locale = Locale.getDefault(),
        override val dateFormatStyle: FormatStyle = FormatStyle.MEDIUM,
        override val timeFormatStyle: FormatStyle = FormatStyle.SHORT,
```

Can you pass a specific Locale to the Dialog and see if it works? What is the current locale, perhaps some rules/ conditions are missing for a specific locale/ pattern?

**Comment by ankur141295** [comment]
Hey, thanks for the reply. My current Locale is en_IN.
As you suggested changing the default values for locale or dateFormatStyle shows the dialogue's expected UI.

In my case setting either of these values shows the expected result:-
locale = Locale.UK
or 
dateFormatStyle = FormatStyle.FULL/FormatStyle.LONG

**Comment by maxkeppeler** [comment]
That's good! However, does that mean it couldn't generate a valid date pattern for the locale of the device? Can you figure out what the pattern was? Ideally, it should still work with the Locale.getDefault().

**Comment by ankur141295** [comment]
Hi @maxkeppeler upon debugging I found out that when using default values for **locale** and **dateFromatStyle**, for my locale i.e. **en_IN** the generated pattern is **dd-MMM-y** and in your _com.maxkeppeler.sheets.date_time.utils.Utils.kt_ file for function **getLocalizedValues** **-** delimiters is missing. Due to this in PickerComponent.kt  **values** state size is 1 and only one composable is generated. 

<img width="1388" alt="Screenshot 2023-02-04 at 10 32 37 PM" src="https://user-images.githubusercontent.com/45303991/216780002-bc18cbfe-f27f-4429-81d4-1c2879e5aaf8.png">

Upon changing **dateFormatStyle = FormatStyle.FULL** the generated pattern is **EEEE, d MMMM, y** and in PickerComponent.kt  **values** state size is 4. 
<img width="1401" alt="Screenshot 2023-02-04 at 10 35 04 PM" src="https://user-images.githubusercontent.com/45303991/216780079-d51af380-6702-4232-a8df-c67c4a58dc64.png">

**Comment by maxkeppeler** [comment]
I have to look through all the possible characters and fix this! 
Thanks man, very helpful as I'm currently keeping myself busy with landscape layouts.
