### ISSUE TITLE
[CalendarDialog] Allows selecting disabled months 

### ISSUE THREAD

**Issue by Nek-12** [maxkeppeler/sheets-compose-dialogs#24]
Although since 1.0.4 disabled dates in the dialog are shown, the calendar dialog's behavior differs for year selection and month selection. Years that are disallowed are not shown for selection, but months are, and selecting them gives the user a list of days where none are active. 

Desired behavior: users can't select months with 0 enabled days.

**Comment by maxkeppeler** [comment]
Likely already fixed with the other calendar related changes, as I can not reproduce it.
