### ISSUE TITLE
[Calendar] Able to select years outside of the specified CalendarTimeline when not using date constraints.

### ISSUE THREAD

**Issue by Nek-12** [maxkeppeler/sheets-compose-dialogs#30]
With the recent changes to the calendar date handling (1.1.0), which were welcome, we noticed that when using calendar timeline, for example FUTURE, although the user can not select a month that is fully in the past, they can select any year they want. All days will be grayed-out for that month upon selection.

Also, upon selecting an invalid year, despite not being able to select months because they all are unavailable, the user can still scroll back and forth between disabled months, circumventing the protection.

**Comment by maxkeppeler** [comment]
I actually would state, that with the boundary, the timeline is obsolete. How do you think about that?

**Comment by Nek-12** [comment]
Well, it is, but I tried to use the boundary and had to write the bounding logic myself and passing it to the dialog, which I thought was cumbersome and ended up not using it. If you choose to remove the timeline property, I will be fine with that as long as there are no bugs, which I think will persist through the change
