### ISSUE TITLE
Android 6.0  CalendarView

### ISSUE THREAD

**Issue by AndroidHJS** [maxkeppeler/sheets-compose-dialogs#36]
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalDate;
        at com.maxkeppeler.sheets.calendar.utils.Constants.<clinit>(Constants.kt:28)
        at com.maxkeppeler.sheets.calendar.models.CalendarConfig.<init>(CalendarConfig.kt:39)

**Comment by maxkeppeler** [comment]
The calendar and time dependent libraries require Java 1.8 / the java.time dependencies. 

```
android {
    ...
    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
    
    dependencies {
        ...
        implementation 'com.android.tools:desugar_jdk_libs:1.1.5'
        ...
  }
}
```
