### ISSUE TITLE
Can't choose a date

### ISSUE THREAD

**Issue by AndroidHJS** [maxkeppeler/sheets-compose-dialogs#41]
![image](https://user-images.githubusercontent.com/22720445/225536390-3ab0d0f1-a5e7-410a-b705-a0a8fd75d2af.png)
The OK button is hidden and cannot be swipe

**Comment by maxkeppeler** [comment]
Does it work for you now?

**Comment by maxkeppeler** [comment]
Is that CalendarView in a bottom sheet?
