### ISSUE TITLE
[API] 1.1.1 Introduces significant breaking changes without deprecation warnings

### ISSUE THREAD

**Issue by Nek-12** [maxkeppeler/sheets-compose-dialogs#43]
Some breaking changes (SheetState -> UseCaseState and rememberSheetState -> rememberUseCaseState, removal of the CalendarTimeline) were introduced in 1.1.1 version without any of these indications about breaking changes:

1. Bumping a major version
2. Introducing deprecation warnings first
3. Providing typealiases
4. Providing an alpha-suffixed version with changes
5. Providing a documented migration path

This led to significant amount of build failures in our project upon upgrading.

Suggestion:
Next time, as this library is stable now, please give users time to migrate to the new API by using a combination of the common practices mentioned above.

**Comment by maxkeppeler** [comment]
Given the extensive scope of the library and the limited free time available to most adults, I have decided not to include deprecation warnings or alpha versions. Although changes were communicated in the release notes, I acknowledge that I could have been more specific about breaking changes and provided migration guides alongside major dependency version upgrades. Rest assured, I will strive to improve my communication in the future to make it easier for devs to adapt to any changes.
