### ISSUE TITLE
[Question] How can we make the start of the day in month selection as Sunday instead of Monday?

### ISSUE THREAD

**Issue by rev0lgenX** [maxkeppeler/sheets-compose-dialogs#49]
Hi , I could not find any documentation or code to change the start of the day as Sunday in month selection. Is it available or not? If not is it possible to add it?

![Screenshot_20230501-165114_AniLib](https://user-images.githubusercontent.com/20517801/235443980-143f99b2-38c8-43d6-9e76-e206af568f85.jpg =250x250)

<img src="https://user-images.githubusercontent.com/20517801/235443980-143f99b2-38c8-43d6-9e76-e206af568f85.jpg" width="282" height="364" />

**Comment by maxkeppeler** [comment]
It's not available yet, I will support it though in the future.

**Comment by maxkeppeler** [comment]
This will work with the next version. This means that for the US, the week will start on Sunday, while for Germany it will start on Mondays.
