### ISSUE TITLE
can we use Their own compose to listDialog item view？

### ISSUE THREAD

**Issue by nideshouhei** [maxkeppeler/sheets-compose-dialogs#5]

**Comment by maxkeppeler** [comment]
I do not see much sense in doing so. If you want to have a list with custom item views, you could just use CoreDialog / InfoDialog and display your own list-item views in the content section. On the other hand, it wouldn't be difficult to allow that. Can you tell me a bit more about your use-case?

**Comment by maxkeppeler** [comment]
I understand and feel the same, especially more configuration options for developers. But I still want to understand your use case. You want to have load dynamic images with coil. The current icon has a size of 24dp. What's the intended size for the image?

**Comment by nideshouhei** [comment]
24dp totally enough

**Comment by maxkeppeler** [comment]
I will plan that for a later version beginning January 2023 as I'm soon in holidays.

**Comment by maxkeppeler** [comment]
I decided against doing this as I do not think it's a common use case. I recommend you to fork the project and add this functionality. Sorry!
