### ISSUE TITLE
[Feature] Provide withButtonView across all views/dialogs

### ISSUE THREAD

**Issue by russellbanks** [maxkeppeler/sheets-compose-dialogs#50]
It's often the case that buttons are not needed at all. For example, bottom sheets already have a convenient way to dismiss them, so a positive button is not needed. Using the view (InfoView, etc) counterparts have more use cases of not needing a button such as providing buttons elsewhere or using animations.

Providing `withButtonView` across all dialogs would be good, or allowing the positive button to be null.

Use case 1:

I want my own button so that I can animate it

![studio64_Q3LdExE2z2](https://user-images.githubusercontent.com/74878137/236924977-be9b02d6-3a6e-49bd-b447-6fc2d2df4c49.gif)

Use case 2:

This is a bottom sheet only for information so I don't need any buttons. The user can just swipe it away

![studio64_TbJ9e0yYfk](https://user-images.githubusercontent.com/74878137/236923416-bddeff6e-f1fc-4b23-a9cc-2a7c02968c0b.png)

**Comment by maxkeppeler** [comment]
Great issue and a change I welcome much as well. 
I will work on this sometime within the next two weeks when I can find time.

**Comment by maxkeppeler** [comment]
Here's an example:
```
    val selectedTimeInSeconds = remember { mutableStateOf<Long>(240) }
    val state = rememberUseCaseState(visible = true, onCloseRequest = { closeSelection() })
    DurationDialog(
        state = state,
        selection = DurationSelection(
            withButtonView = false,
        ) { newTimeInSeconds ->
            selectedTimeInSeconds.value = newTimeInSeconds
        },
        config = DurationConfig(
            timeFormat = DurationFormat.HH_MM_SS,
            currentTime = selectedTimeInSeconds.value,
        ),
    )
    val coroutineScope = rememberCoroutineScope()
    coroutineScope.launch {
        delay(5000)
        state.invokePositiveAction()
    Log.d("DurationSample1", "DurationSample1: ${selectedTimeInSeconds.value}")
    }
```
