### ISSUE TITLE
Allow OptionSheet icons to be in colour

### ISSUE THREAD

**Issue by russellbanks** [maxkeppeler/sheets-compose-dialogs#56]
Same as https://github.com/maxkeppeler/sheets/issues/83 but for Compose dialogs.

There should be an option to keep the icon as is without any tinting at all.

![studio64_BVb8pByJ1s](https://github.com/maxkeppeler/sheets-compose-dialogs/assets/74878137/06e4e285-6b28-4aeb-a0cb-d16600def75f)

I want the user to be able to choose an image but it looks like that rather than retaining all its colours.

**Comment by maxkeppeler** [comment]
Did you try to add a tint of color, "Color.Unspecified" which according to the Icon component would not apply a tint to the icon?

**Comment by russellbanks** [comment]
> Did you try to add a tint of color, "Color.Unspecified" which according to the Icon component would not apply a tint to the icon?

`Color.Unspecified` turns it black/white

![studio64_pnbgruqCRs](https://github.com/maxkeppeler/sheets-compose-dialogs/assets/74878137/1eccb2be-bf4c-498e-91a3-0572d3039c15)

**Comment by maxkeppeler** [comment]
Hmm I just checked and this seems to work:
```

 icon = IconSource(
                R.drawable.ic_fruit_apple,
                tint = Color.Unspecified
            )
```
It's gray by default and the color is kept. When I use Color.RED, it's red. If I remove tint / keep it null, it uses the secondary color. 

I guess you are not using a DrawableRes?

**Comment by russellbanks** [comment]
I was doing it as a painterResource before, but it's still like that even with drawableRes:

```kotlin
if (imageSheetVisible) {
    ModalBottomSheet(
        onDismissRequest = { imageSheetVisible = false },
        sheetState = imageSheetState
    ) {
        OptionView(
            useCaseState = rememberUseCaseState(),
            selection = OptionSelection.Single(
                options = listOf(
                    Option(
                        icon = IconSource(
                            drawableRes = R.drawable.image_anahata,
                            tint = Color.Unspecified
                        ),
                        titleText = "",
                    )
                ),
                onSelectOption = { index, option ->
                }
            ),
            config = OptionConfig(
                mode = DisplayMode.GRID_VERTICAL,
            )
        )
    }
}
```

**Comment by maxkeppeler** [comment]
My example was with the header. 
```
   header = Header.Default(
            "Select time",
            icon = IconSource(
                R.drawable.ic_fruit_apple,
                tint = Color.Unspecified
            )
        ),
```

**Comment by maxkeppeler** [comment]
For the OptionView it makes sense if it doesn't work as it enforces currently the icon color.
 ```
val iconColor = if (option.selected) MaterialTheme.colorScheme.primary
    else MaterialTheme.colorScheme.onSurface
```
