### ISSUE TITLE
How do I change the text used in calendar

### ISSUE THREAD

**Issue by thomasponzo-dev** [maxkeppeler/sheets-compose-dialogs#58]
I want to change the text Select month to my own language and also  Select year how can I do this?

**Comment by maxkeppeler** [comment]
What do you mean by "to your language"? Currently, it is in English, and are you looking to have it translated into your language? These strings are part of the library and require translation in the string files. May I know which language you need?

**Comment by thomasponzo-dev** [comment]
dutch select month should be selecteer maand and select year should be select selecteer jaartal

**Comment by maxkeppeler** [comment]
Are they correct?

<string name="scd_calendar_dialog_select_month">Selecteer maand</string>
<string name="scd_calendar_dialog_next_month">Volgende maand</string>
<string name="scd_calendar_dialog_prev_month">Vorige maand</string>
<string name="scd_calendar_dialog_next_week">Volgende week</string>
<string name="scd_calendar_dialog_prev_week">Vorige week</string>
<string name="scd_calendar_dialog_select_year">Selecteer jaar</string>

**Comment by thomasponzo-dev** [comment]
yes they are correct now

**Comment by thomasponzo-dev** [comment]
When are they gonna be updated?

**Comment by maxkeppeler** [comment]
With the release of the next version.

**Comment by thomasponzo-dev** [comment]
Awesome thanks for adding it in :D amazing library. Do you have a rough estimate when the next version is released?

**Comment by maxkeppeler** [comment]
I do not have any time this weekend, but I will attempt to fix some more issues and release a new version the weekend after...
