### ISSUE TITLE
[Feature] Provide Bottom Sheets

### ISSUE THREAD

**Issue by russellbanks** [maxkeppeler/sheets-compose-dialogs#59]
Bottom sheets were introduced in Material3 1.1.0. It would be nice to have bottom sheets from this library rather than using the view counterparts embdedded in bottom sheets.

**Comment by maxkeppeler** [comment]
I'm having a hard time making the UseCaseState and the SheetState work together. Even after I hide the bottom sheet, something seems to be blocking all the clicks. I can't figure out why this is happening, so I won't include it in the next version. See the related branch feature/bottom_sheets if you are curious.
