### ISSUE TITLE
Library introduces a heavy `material-icons-extended` as a dependency into the resulting APK

### ISSUE THREAD

**Issue by Nek-12** [maxkeppeler/sheets-compose-dialogs#6]
Including this as a dependency increases the resulting APK size by a significant margin and adds overhead for builds run with R8.
Material-icons-extended should not be included into the library because that dependency contains a lot of unused code

Proposed solution: 
Copy the code of required icons directly into the source code of the library or provide a way for users to supply their own icons instead

**Comment by maxkeppeler** [comment]
Agree! I doubt I will even need the icons for the lib, but more likely for the sample app.

**Comment by Nek-12** [comment]
Hello, any progress on this?

**Comment by maxkeppeler** [comment]
Working on a flexible solution where anyone can specify the style used for the icons, and only the specific icons would be included in the project. The dependency material-icons-extended is removed. I need a bit more time.

**Comment by Nek-12** [comment]
Hmmh, I see that LibIcons is an object and cannot be replaced when passing the config. Wouldn't it disallow icon customization beyond what's used in the library? I'd suggest passing a painter object as a parameter. I use icon fonts for example and they don't have an object I can pass, so I pass painters around.

**Comment by maxkeppeler** [comment]
The use-case view icons allow users to select any style they want, which can be seen as customization compared to before. When it comes to the views themselves, like the Option-Dialog/Option-View, anything can be passed to the icon that is displayed within the options. This uses the IconSource class, which accepts any input. 

Is this level of customization really necessary? I personally feel like developers would at this point fork the project as they require specific changes.

**Comment by Nek-12** [comment]
It's up to you at this point - whether you want to be opinionated or not
