### ISSUE TITLE
[Question] Min version SDK.

### ISSUE THREAD

**Issue by ButovAndersen** [maxkeppeler/sheets-compose-dialogs#60]
Where I can find information about min version sdk?
In AndroidManifest.xml I saw min 21 but for LocalData from java package you need min 26.
How it's can work for api 21?

**Comment by ButovAndersen** [comment]
Run app on Android 5 (emulator)
`                 java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalDate;
                 	at com.maxkeppeler.sheets.calendar.utils.Constants.<clinit>(Constants.kt:28)
                 	at com.maxkeppeler.sheets.calendar.models.CalendarConfig.<init>(CalendarConfig.kt:40)`

**Comment by ButovAndersen** [comment]
We use threetenbp it has API like Java DateTime but for threetenbp need min sdk 21.
What do you think about supporting sdk 21? @maxkeppeler

**Comment by Nek-12** [comment]
You should probably just use desugaring to support Java 8 apis

**Comment by maxkeppeler** [comment]
Nek-12 is right. For the modules that use Java Time, you have to use desugaring.

**Comment by ButovAndersen** [comment]
@Nek-12 @maxkeppeler Thanks guys! Really work and for me it's something new!!! I'm a shok)))
