### ISSUE TITLE
[Bug] Settings "12:00 AM" on the time picker resets the time to 12:00 PM instead

### ISSUE THREAD

**Issue by Nek-12** [maxkeppeler/sheets-compose-dialogs#64]
1. Open a time picker with AM/PM mode enabled
2. Set the time to 12:00 AM **explicitly** i.e by tapping the AM/PM chip
3. Click "OK" 
4. Dialog returns "12:00 PM"
5. Set the time to 12:00 PM, choosing "PM" explicitly
6. Dialog returns "00:00 AM".

**Comment by luisguzman2098** [comment]
Como puedo obtener el valor seleccion de AM o PM para ponerlo en un string?

**Comment by Nek-12** [comment]
How is this related to the issue? @luisguzman2098

**Comment by Nek-12** [comment]
@maxkeppeler Any progress on this?

**Comment by Nek-12** [comment]
@maxkeppeler Is there any progress on this? Would you be willing to merge a PR that fixes the issue?

**Comment by maxkeppeler** [comment]
Yes, contributions are welcome! Just no hacky workarounds but clean solutions. Considering my free time I would be very thankful for a PR that fixes this issue!

**Comment by Nek-12** [comment]
Yes, I noticed that you are very busy lately. I'll prepare a PR, this should be a simple but very important fix

**Comment by maxkeppeler** [comment]
Where's the PR? 😆

**Comment by Nek-12** [comment]
> Where's the PR? 😆

I completely forgot about this 🙃
