### ISSUE TITLE
Month text font is too large

### ISSUE THREAD

**Issue by ksog66** [maxkeppeler/sheets-compose-dialogs#68]
![WhatsApp Image 2023-09-04 at 23 20 49](https://github.com/maxkeppeler/sheets-compose-dialogs/assets/70816971/e7a79fbc-3d3b-4b27-914e-b8e49c9dd6c0)

I am using Moderno font and i couldn't find anything in documentation to change the size of this text

**Comment by Nek-12** [comment]
It's using a material theme you have defined. Your headline / title texts are too large (set up in Material Theme) try to use recommended values for those
