### ISSUE TITLE
Language of calendar don't change when changing app language 

### ISSUE THREAD

**Issue by MohamedBa3ly** [maxkeppeler/sheets-compose-dialogs#71]
When user choose any language , calendar [ Month ]  didn't change , still Englich , and when change language for second time it change for language that user choose first !!

**Comment by maxkeppeler** [comment]
Changing the system language changes also the language of the library, which is a standard behavior. I was not able to replicate your issue, can you be more specific? Thank you 😊
Spanish to English
<img src="https://github.com/maxkeppeler/sheets-compose-dialogs/assets/15075376/65ddfc07-8511-45a9-82ef-c52d3ab238bd" width="250">
<img src="https://github.com/maxkeppeler/sheets-compose-dialogs/assets/15075376/e07cde66-c485-4366-a745-0e4fff722bed" width="250">
