### ISSUE TITLE
Feature: Week Number in Calendar Component (Optional)

### ISSUE THREAD

**Issue by nikqig** [maxkeppeler/sheets-compose-dialogs#79]
I've been using your calendar library for a project and it's been incredibly helpful. I have a specific feature query regarding the display of week numbers ("Uge nr") within the calendar, a common requirement in Denmark.

Could you tell me if your calendar component natively supports week number calculation and display, considering locale-specific settings (like week start day)? If this feature isn't currently available, I would appreciate any help on how to customize or extend the UI integration to include week numbers.

Your help would be appreciated. Thanks in advance and great job creating this tool.

**Comment by maxkeppeler** [comment]
Hi Nikqig, I'm happy to hear that other developers like and can use the library! Could you show me how calendars typically look there with the week numbers? The general issue I've had so far with the calendar dialog/view was that the space was usually limited. I wonder if there's enough space to display the week number, and also in which ways it makes sense. If I know that, I will be able to add it. Can you show me some examples?

**Comment by nikqig** [comment]
Yeah ofcourse! Here you go: 

![thumbnail_IMG_2189](https://github.com/maxkeppeler/sheets-compose-dialogs/assets/155681489/75b0ed99-4d1b-4582-b96a-546f3cd0aa25)

![thumbnail_IMG_2188](https://github.com/maxkeppeler/sheets-compose-dialogs/assets/155681489/804220e4-af51-490b-b370-2414e2f0d673)

As you can see, the week numbers are compact and don't occupy a lot of space on the left side :)

**Comment by maxkeppeler** [comment]
I accept it as a feature, then. My time is limited though, and I'm experiencing a small personal crisis, so I will do it when I can and feel like it. I hope that's understandable!

**Comment by maxkeppeler** [comment]
Calendar weeks for the monthly and weekly view are supported in the upcoming version.

**Comment by maxkeppeler** [comment]
Use `displayCalendarWeeks` in the `CalendarConfig`.
