### ISSUE TITLE
Dialogs are cut in landscape mode

### ISSUE THREAD

**Issue by Nek-12** [maxkeppeler/sheets-compose-dialogs#8]
When screen height is less than the minimum height of the dialog, it's unusable. 

<details>
  <summary>Screenshot</summary>
  
 
![Screenshot_20221108-152910](https://user-images.githubusercontent.com/46318640/200564116-3849867f-a909-4bf6-b9fa-20640a7f65da.png)

  
</details>

**Comment by maxkeppeler** [comment]
That's not easily fixable. Also, from my experience, most apps seem to force portrait mode to avoid such problems. The lib does not support landscape mode right now on smartphones where the height is very narrow. 
Now, for this specific use-case / the Clock Dialog/ View - what would the best approach be?
I thought about it before, and from my view I would need to split the content into 2 views - the display clock time part and the keyboard. For this one it might be easy, but some other use-case views can not be divided, while they are not scrollable either. 

I will start working on "landscape" support soon. But I guess it would make only sense to display the landscape-design for smartphones / smaller screens.

**Comment by Nek-12** [comment]
Hello, sorry for long time without an answer. Forgot about this issue. 
Regarding forcing portrait mode, I'd argue against this. Most quality apps support tablets, and consequently, landscape orientation. If this library is to be used in commercial apps, landscape layout is a must. 

About the dialog layout, what we could do is take inspiration from how Google does this. An example is the calculator app, which changes the layout of the calculator buttons.
About the design - in my humble opinion, it's up to you. Since this is a "Material Dialogs" library, I'd advise to follow google's practices and designs as close as possible.

<details>
  <summary>Screenshot</summary>
  
![Screenshot_20221203-125745_Calculator](https://user-images.githubusercontent.com/46318640/205439127-c9e84b0c-232e-4b91-9e4a-fd81ef4575e9.png)
![Screenshot_20221203-125749_Calculator](https://user-images.githubusercontent.com/46318640/205439128-82f964f3-e51b-4772-993f-caeb9f0c9b79.png)
    
</details>

**Comment by maxkeppeler** [comment]
In case of the calculator app, the landscape made just reveals additional input methods and displays them over the width while reducing the sizes, so It's a bit different while they still can work with way more space. But I agree to you, and I also would prefer landscape support with a nice and working custom layout. I will make some sketches and give it some thoughts, thought that will probably first a task in the next year due to my holidays soon!

**Comment by maxkeppeler** [comment]
Slowly working on it. See https://twitter.com/max_keppeler/status/1617266472174108672
That's going to be quite some work for each use-case view.

**Comment by Nek-12** [comment]
Thanks for the update! Sheets landscape is one of the last things our team is waiting for for a full tablet support. 

I'm also thinking about foldables lately, because some foldables have a hinge in the middle that can be quite [obstructing](https://devblogs.microsoft.com/surface-duo/large-screen-design-patterns/)

**Comment by maxkeppeler** [comment]
1. Well on tablets, the layouts won't be cut as there is way more space than there is on a Smartphone in landscape mode. 

The Guidelines are great, but they lack information on what is supposed to happen on a Smartphone in Landscape mode. There's no way, that there would be space for a header, even with the new landscape view I shared. So, just remove the header in the Landscape mode on a Smartphone?

https://m3.material.io/components/dialogs/guidelines

3.  For large displays, tablet or foldables, the guidelines say, that you can just position the dialog as you need it. 
![image](https://user-images.githubusercontent.com/15075376/213984444-d3410e04-da75-4052-aa97-ccf60e49d6c5.png)

**Comment by maxkeppeler** [comment]
This library mainly offers the use-case views. The dialogs are just making use of the Dialog Composable, which does not seem to support that yet. At least not in the form, as Popup works in Compose.

**Comment by maxkeppeler** [comment]
There's no way to design a compact view / dialog for a smartphone in landscape mode when using the defaultPlatformWidth for the dialog. I added a landscape layout for the clock & duration & calendar month view and made a small modification for the color view. When using a header additionally, it will always be cut off. There's just not enough space to place it anywhere. I only enable the landscape layout if the device appears to be a smartphone and some other conditions.

**Comment by Nek-12** [comment]
Left a small comment in the diff for you regarding your comment about orientation here

**Comment by Nek-12** [comment]
@maxkeppeler Hey, any chance of making a release with this included? Seems like you added support but haven't published a release. Anything holding you back that I can help with?

**Comment by maxkeppeler** [comment]
I will attempt to fix the current bugs and build a new release right after it. Probably today, UTC+1 time. I wanted to release MD2 dependencies alongside on the separate branch, but didn't have enough time to work on that. I will add support for MD2 with a later release and get the current bug fixes and improvements out soon.
