### ISSUE TITLE
[Question] Setting the initial week

### ISSUE THREAD

**Issue by nikqig** [maxkeppeler/sheets-compose-dialogs#80]
I have a question regarding setting the initial week view based on a selected date.

I noticed the CalendarData class has a weekCameraDate property, which seems to control the starting point of the week view. I'm trying to figure out how to set this property so that the calendar displays the week containing a specific date that the user has selected.
In the application, there are two instances where the user interacts with the calendar. Initially, the user selects a date from a monthly calendar view. Later, in a different part of the app, I need to display a weekly calendar view.
I want this weekly calendar to open showing the week that includes the previously selected date.

My initial attempt at implementing this functionality. Here's the relevant code snippet:

```Kotlin
@Composable
fun CalendarWeek(
    calendarState: UseCaseState,
    calendarViewModel: CalendarViewModel,
    onSelectDate: (LocalDate) -> Unit,
) {
    val danishLocale = Locale("da", "DK") // Danish Locale
    val headerText by calendarViewModel.currentHeaderText.observeAsState("")

    CalendarDialog(
        state = calendarState,
        selection = CalendarSelection.Date(
            selectedDate = calendarViewModel.selectedDate.value, //this 
            onSelectDate = onSelectDate,
            positiveButton = SelectionButton(text = "Vælg"),
            negativeButton = SelectionButton(text = "Annuller"),
            onNegativeClick = { calendarViewModel.resetSelectedEndDate() }
        ),
        header = Header.Custom { CustomCalendarHeader(headerText) },
        config = CalendarConfig(
            locale = danishLocale,
            style = CalendarStyle.WEEK,
        )
    )
}
```
And here's how I use CalendarWeek:
```Kotlin
CalendarWeek(
    calendarState = calendarViewModel.calendarState,
    calendarViewModel = calendarViewModel,
    onSelectDate = { date ->
        
    }
)
```
With this implementation, the calendar opens to the correct week based on the selectedDate from calendarViewModel. However, this approach also highlights the selectedDate when the weekly calendar opens, which I would like to avoid. I'd prefer the calendar to open to the week of the selected date without highlighting any specific date.

Again great work! Sorry for spamming you with questions.

**Comment by maxkeppeler** [comment]
I would like to understand and help. With highlighting, you mean the selectedDate is displayed/ marked as highlighted? But the only way to not highlight them, is to not display any selectedDate. 🤔

**Comment by maxkeppeler** [comment]
Oh. So currently it's not possible to have a custom camera date. I will support it with the next version. :)
