### ISSUE TITLE
some question about "CalendarSelection.Dates"

### ISSUE THREAD

**Issue by nideshouhei** [maxkeppeler/sheets-compose-dialogs#9]
when i using "CalendarDialog"  , now i want to Select multiple dates , everyThings is  perfect . we have “CalendarSelection.Dates” ，but this is have no effect in “CalendarSelection.Dates.selectedDates”. When I open Dialog a second time  dialog does not display the contents of my last selection. my code Abstract :"  val selectedDates = remember { mutableStateOf(listOf<LocalDate>()) } , selectedDates = selectedDates.value,"

**Comment by maxkeppeler** [comment]
Hey. Will be fixed, I already noticed it to while using it. This behavior actually can make sense in some cases if it's embedded in a container like the _BottomSheet_ or _PopUp_. I will change the standard behavior to as what would be expected.

**Comment by maxkeppeler** [comment]
Will be the future version 1.0.2
